<a href="https://colab.research.google.com/github/Sairam-04/ML-Packages/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Pandas:

Pandas is an open-source, BSD-licensed Python library providing high-performance, easy-to-use data structures and data analysis tools for the Python programming language. Python with Pandas is used in a wide range of fields including academic and commercial domains including finance, economics, Statistics, analytics, etc. In this tutorial, we will learn the various features of Python Pandas and how to use them in practice.

In [1]:
import pandas as pd
import numpy as np

In [2]:
#Creating Dataframe
data = np.arange(0,20).reshape(5,4)
df = pd.DataFrame(data, index = ['Row1','Row2','Row3','Row4','Row5'], columns=["Column1","Column2","Column3","Column4"])

In [3]:
print(df)

      Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19


In [4]:
df

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [5]:
df.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [6]:
df.head(2)

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7

In [7]:
#df.describe()

In [8]:
# creating csv file
df.to_csv('sample1.csv')

In [9]:
#Acessing elements
# 1. .loc[]  2. .iloc[]

df.loc['Row1']

Column1    0
Column2    1
Column3    2
Column4    3
Name: Row1, dtype: int64

In [10]:
type(df.loc['Row1'])

pandas.core.series.Series

In [11]:
df[['Column1','Column2']]

Column1  Column2
Row1        0        1
Row2        4        5
Row3        8        9
Row4       12       13
Row5       16       17

In [12]:
df[['Column1','Column2']]

Column1  Column2
Row1        0        1
Row2        4        5
Row3        8        9
Row4       12       13
Row5       16       17

In [13]:
# INdexing
df.loc['Row1']['Column3']

2

In [14]:
# .iloc[]

df.iloc[0:2,1:2]

Column2
Row1        1
Row2        5

In [15]:
df.iloc[1:4,0:2]

Column1  Column2
Row2        4        5
Row3        8        9
Row4       12       13

In [16]:
df.iloc[:,1:]

Column2  Column3  Column4
Row1        1        2        3
Row2        5        6        7
Row3        9       10       11
Row4       13       14       15
Row5       17       18       19

In [17]:
# If we have more than 1row or 1 col type is data frame

type(df.iloc[:,:])

pandas.core.frame.DataFrame

In [18]:
df.iloc[0:3,0]

Row1    0
Row2    4
Row3    8
Name: Column1, dtype: int64

In [19]:
# If we have 1row or 1 col type is series

type(df.iloc[0:3,0]) 

pandas.core.series.Series

In [20]:
# Converting DataFrame into an array
df.iloc[:,:].values

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [21]:
df.iloc[:,:].values.shape

(5, 4)

In [22]:
# Finding Null values in dataframe
df.isnull().sum()

Column1    0
Column2    0
Column3    0
Column4    0
dtype: int64

In [23]:
df.value_counts()

Column1  Column2  Column3  Column4
16       17       18       19         1
12       13       14       15         1
8        9        10       11         1
4        5        6        7          1
0        1        2        3          1
dtype: int64

In [24]:
df['Column1'].unique() #unique values in dataframe

array([ 0,  4,  8, 12, 16])

In [25]:
data = pd.read_csv('mercedesbenz.csv')

In [26]:
data.shape

(4209, 378)

In [27]:
data.head(10)

ID       y  X0 X1  X2 X3 X4  ... X378 X379 X380  X382  X383  X384  X385
0   0  130.81   k  v  at  a  d  ...    0    0    0     0     0     0     0
1   6   88.53   k  t  av  e  d  ...    0    0    0     0     0     0     0
2   7   76.26  az  w   n  c  d  ...    0    0    0     1     0     0     0
3   9   80.62  az  t   n  f  d  ...    0    0    0     0     0     0     0
4  13   78.02  az  v   n  f  d  ...    0    0    0     0     0     0     0
5  18   92.93   t  b   e  c  d  ...    0    0    0     0     0     0     0
6  24  128.76  al  r   e  f  d  ...    0    0    0     0     0     0     0
7  25   91.91   o  l  as  f  d  ...    0    0    0     0     0     0     0
8  27  108.67   w  s  as  e  d  ...    0    0    0     0     0     0     0
9  30  126.99   j  b  aq  c  d  ...    0    0    0     0     0     0     0

[10 rows x 378 columns]

In [28]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Columns: 378 entries, ID to X385
dtypes: float64(1), int64(369), object(8)
memory usage: 12.1+ MB


In [29]:
# Only int and float values will be considered
data.describe()

ID            y  ...         X384         X385
count  4209.000000  4209.000000  ...  4209.000000  4209.000000
mean   4205.960798   100.669318  ...     0.000475     0.001426
std    2437.608688    12.679381  ...     0.021796     0.037734
min       0.000000    72.110000  ...     0.000000     0.000000
25%    2095.000000    90.820000  ...     0.000000     0.000000
50%    4220.000000    99.150000  ...     0.000000     0.000000
75%    6314.000000   109.010000  ...     0.000000     0.000000
max    8417.000000   265.320000  ...     1.000000     1.000000

[8 rows x 370 columns]

In [30]:
data['X0'].value_counts()

z     360
ak    349
y     324
ay    313
t     306
x     300
o     269
f     227
n     195
w     182
j     181
az    175
aj    151
s     106
ap    103
h      75
d      73
al     67
v      36
af     35
ai     34
m      34
e      32
ba     27
at     25
a      21
ax     19
am     18
aq     18
i      18
u      17
l      16
aw     16
ad     14
k      11
b      11
au     11
r      10
as     10
bc      6
ao      4
c       3
aa      2
q       2
ab      1
g       1
ac      1
Name: X0, dtype: int64

# Creating CSV 

In [31]:
from io import StringIO, BytesIO
d = ('col1,col2,col3\n'
         'X,Y,1\n'
         'a,b,2\n'
         'c,d,3'
       )

In [32]:
type(d)

str

In [33]:
pd.read_csv(StringIO(d))

col1 col2  col3
0    X    Y     1
1    a    b     2
2    c    d     3

In [34]:
a = pd.read_csv(StringIO(d), usecols=['col1','col3'])
a

col1  col3
0    X     1
1    a     2
2    c     3

In [35]:
data2 = (
    'a,b,c,d\n'
    '1,2,3,4\n'
    '5,6,7,8\n'
    '9,10,11,12\n'
)

In [36]:
b = pd.read_csv(StringIO(data2),dtype=object)

In [37]:
b

a   b   c   d
0  1   2   3   4
1  5   6   7   8
2  9  10  11  12

In [38]:
b['a']

0    1
1    5
2    9
Name: a, dtype: object

In [39]:
b = pd.read_csv(StringIO(data2),dtype=int)

In [40]:
b['a']

0    1
1    5
2    9
Name: a, dtype: int64

In [41]:
b = pd.read_csv(StringIO(data2),dtype=float)
b['b']

0     2.0
1     6.0
2    10.0
Name: b, dtype: float64

In [42]:
b = pd.read_csv(StringIO(data2),dtype = {'b':float,'a':int,'c':object})
b.dtypes

a      int64
b    float64
c     object
d      int64
dtype: object

In [43]:
data3 = (
    'index,a,b,c,d\n'
    '1,2,3,4,13\n'
    '5,6,7,8,14\n'
    '9,10,11,12,15\n'
)

In [44]:
c = pd.read_csv(StringIO(data3))
c

index   a   b   c   d
0      1   2   3   4  13
1      5   6   7   8  14
2      9  10  11  12  15

In [45]:
c = pd.read_csv(StringIO(data3),index_col=3)
c

index   a   b   d
c                    
4       1   2   3  13
8       5   6   7  14
12      9  10  11  15

In [46]:
c = pd.read_csv(StringIO(data3))
c

index   a   b   c   d
0      1   2   3   4  13
1      5   6   7   8  14
2      9  10  11  12  15

In [47]:
c = pd.read_csv(StringIO(data3),index_col=False)
c

index   a   b   c   d
0      1   2   3   4  13
1      5   6   7   8  14
2      9  10  11  12  15

In [48]:
c.values

array([[ 1,  2,  3,  4, 13],
       [ 5,  6,  7,  8, 14],
       [ 9, 10, 11, 12, 15]])